site_name: Image+
docs_dir: core/components/imageplus/docs
site_dir: _build/site

repo_url: https://github.com/Jako/ImagePlus

pages:
- Home: 'index.md'
- Installation: 'installation.md'
- Getting Started: 'getting-started.md'
- Usage: 'usage.md'
- Examples: 'examples.md'
- Contributors: 'contributors.md'
- Donate: 'donate.md'

theme: flatly

markdown_extensions:
    - footnotes
    - tables